"""test

Revision ID: 25c00dcb472c
Revises: 4013ac40d572
Create Date: 2026-05-05 17:52:37.198951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c00dcb472c'
down_revision: Union[str, Sequence[str], None] = '4013ac40d572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Department', ['departmentID'], ['departmentID'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departmentID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Department', ['departmentID'], ['departmentID'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departmentID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Department', ['departmentID'], ['departmentID'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('departmentID')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('departmentID')

    with op.batch_alter_table('Account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
